---
title: "Semana 11 - ejercicios"
author: "Ramos Marchand Harumy"
format: html
editor: visual
---

## EJERCICIO 2

```{r}

#COEFICIENTE BETA
beta<--0.405

#Cálculo del Hazard ratio
HR<-exp(beta)

#mostrar resultado
HR
```

```{r}
#interpretación
cat("Hazard ratio=",round(HR,3),"\n")
cat("El programa reduce el riesgo en",round((1-HR)*100,1),"% respecto al grupo de control.")
```

## EJERCICIO 3

```{r}
#Hazard Ratio reportado
HR<-1.80

#Incremento porcentual del riesgo
incremento<-(HR-1)*100

#MOSTRAR RESULTADO
cat("Hazard ratio=",HR,"\n")
cat("Incremento del riesgo=",incremento,"%\n")
```

## EJERCICIO 4

```{r}
#COEFICIENTE BETA
  beta<--0.693

#Cálculo del Hazard ratio

HR<-exp(beta)

#mostrar resultado
HR


#interpretación
cat("Hazard ratio=",round(HR,3),"\n")
cat("El programa reduce el riesgo en",round((1-HR)*100,1),"% respecto al grupo de control.")
```

## EJERCICIO 5

```{r}
# COEFICIENTE BETA
beta <- 0.182

# Cálculo del Hazard Ratio
HR <- exp(beta)

# Mostrar resultado
HR
```

```{r}
# Interpretación
cat("Hazard ratio =", round(HR, 2), "\n")
cat("Cada año adicional de edad aumenta el riesgo en",
    round((HR - 1) * 100, 0),
    "% aproximadamente.")
```

## EJERCICIOS PROPUESTOS

Ejercicio 1

```{r}
# COEFICIENTE BETA
beta <- 0.405

# Cálculo del Hazard Ratio
HR <- exp(beta)

# Mostrar resultado
HR
```

```{r}
# Interpretación
cat("Hazard ratio =", round(HR,2), "\n")
cat("El riesgo aumenta en", round((HR-1)*100,1), "% aproximadamente.")
```

Ejercicio 2

```{r}
# HAZARD RATIO REPORTADO
HR <- 0.75

# Reducción porcentual del riesgo
reduccion <- (1 - HR) * 100

# Mostrar resultado
cat("Hazard ratio =", HR, "\n")
cat("Reducción del riesgo =", reduccion, "%\n")
```

Ejercicio 3

```{r}
# HAZARD RATIO REPORTADO
HR <- 1.35

# Incremento porcentual del riesgo
incremento <- (HR - 1) * 100

# Mostrar resultado
cat("Hazard ratio =", HR, "\n")
cat("Incremento del riesgo =", incremento, "%\n")
```

Ejercicio 4

```{r}
# COEFICIENTE BETA
beta <- -1.20

# Cálculo del Hazard Ratio
HR <- exp(beta)

# Mostrar resultado
HR
```

```{r}
# Interpretación
cat("Hazard ratio =", round(HR,2), "\n")
cat("Reducción del riesgo =",
    round((1 - HR) * 100,1),
    "%\n")
```

Ejercicio 5

```{r}
# HAZARD RATIO REPORTADO
HR <- 2.10

# Incremento porcentual del riesgo
incremento <- (HR - 1) * 100

# Mostrar resultado
cat("Hazard ratio =", HR, "\n")
cat("Incremento del riesgo =", incremento, "%\n")
```
